name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make 
      run: make
    - name: ./murk compile tests/test1.murk
      run: ./murk compile tests/test1.murk
    - name: ./murk compile tests/test2.murk
      run: ./murk compile tests/test2.murk
